version: '3'
services:
  app:
    image: haendlerbund/laravel-base:7.3-node
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app/:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=my_db"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - backend

networks:
  backend: